### ISSUE TITLE
ENOL_APP missing in AfV database

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#455] opened 2024-09-19 15:31 UTC
118.250

![image](https://github.com/user-attachments/assets/542ba4a5-6d67-4a04-a4ae-9ec1bbf1a66f)

**Comment by Adrian2k** [comment] 2024-09-19 15:38
Duplicate of #412

**Closed by Adrian2k** 2024-09-19 15:38 UTC
