### ISSUE TITLE
Misplaced element in ACC TAG?

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#452] opened 2024-09-14 09:32 UTC
Tag family: ACC
Type: Tagged
![image](https://github.com/user-attachments/assets/9fbc1503-f059-46a0-84ed-3c2cd4d88fdb)

I believe the vertical speed is not supposed to be above C/S?

**Comment by Sanderli25** [comment] 2024-09-14 14:20
Duplicate of issue #444

**Closed** 2024-09-14 14:20 UTC
Labels: bug
